### ISSUE TITLE
Timeout for RFID swipe on "Report Issue"

### ISSUE THREAD

**Issue by bkgoodman** [makeitlabs/ratt#4]
"Report issue" should have a timeout waiting for the user's RFID swipe. It currently has none. It gets confusing when the next user swipes-in (maybe significantly later) - and inadvertently sends the last-user's pending message, and is not logged in.

(If it does have one - it's probably too long).

**Comment by tangentaudio** [comment]
Thanks, I did note this at one point but forgot about it.

**Comment by tangentaudio** [comment]
Fixed, there is now a 30 second timeout for the entire issue reporting process.  Keypresses reset the timeout timer.  Also added an "exit (no issue to report" issue as first item, and fixed bug with empty issue report when exiting.
