### ISSUE TITLE
Option to remain logged-in when idle

### ISSUE THREAD

**Issue by bkgoodman** [makeitlabs/ratt#6]
When you are working - and clock is ticking down to auto-timeout, it would be nice to have SOME way of preventing this - like [preferably] hitting a button or _even_ re-swiping RFID.

It sucks to watch the clock count down when you're not ready to run - knowing that you'll have to re-badge-in in 15 seconds.

**Comment by tangentaudio** [comment]
Yes - this one is easy and I've been meaning to do it.   I think I will allow a button press to restart the countdown.

Re-swiping RFID would at least prevent coat-tailing but I think it's probably a bit too inconvenient to be worth it.  We can also increase the default timeout on the particular tool if it seems a bit too short.

**Comment by tangentaudio** [comment]
Fixed, any user may now simply press the blue button when logged in to reset their idle timer to the value configured by `[Personality] TimeoutSeconds` in the config file.
