### ISSUE TITLE
Laser wouldn't work - Half-stuck in "zero-XY mode"?

### ISSUE THREAD

**Issue by bkgoodman** [makeitlabs/ratt#8]
I was using the laser - everything was fine. Powering on and off, timing out, re-logging in, etc.

At one point I noticed the RATT was beeping - like it does when it is waiting for Zero-XY. I had already done the homing, and the screen was NOT telling me to do so again. It was a bit of an unexplained annoyance. 

At one point I went to cut - and laser would not fire. I checked everything - tried re badging in, even tried re-homing laser. It kept beeping, and still would not fire.

Eventually I killed power to RATT. When it came back up - I homed - and all worked well from there.

**Comment by tangentaudio** [comment]
Closing this issue since we have retired the Rabbit laser.  The bugs still exist, but no longer impact day-to-day operation.
